server:
  port: 8090

spring:
  application:
    name: user-service
    data:
        mongodb:
            uri: mongodb://test-mongo:27017/test_movie
            database: test_movie
            port: 27017
